version: "3.9"

services:
  sqldata:
    image: mcr.microsoft.com/mssql/server:2017-latest
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "Password1234"
      ACCEPT_EULA: "Y"
    volumes:
      - ./backup:/var/opt/mssql/backup
    